### ISSUE TITLE
Not recognizing flowchart

### ISSUE THREAD

**Issue by kghrfp** [renanlecaro/mermaid-gdocs#19] opened 2020-10-27 02:53 UTC
Trying to edit a flowchart that I created in Google Docs using the Mermaid Add On.  
After several rounds of edits, it no longer recognized the chart as one created in mermaid, and I get the following pop-up error:

"Please select an existing chart created with this app first."
![image](https://user-images.githubusercontent.com/73510847/97251221-d4c7b080-17dd-11eb-8107-495ba4933dbf.png)

Seems to have happened afer I resized and poisitioned it within the document.  
Any suggestions? I exited out, and relaunched the google doc, but still happening.

TIA.

**Comment by cobbce** [comment] 2021-01-23 22:35
Same issue-- I did resize / reposition the chart also.

**Comment by renanlecaro** [comment] 2021-03-20 15:58
Gosh i seem to always miss the issues on this repo. The problem is the positioning of the image. If you reset the positioning of the image to "inline" (basically, how it was when inserted) you should be able to edit the source, save, then put it back to floating or whatever mode you need. It's not convenient, i know :/

**Comment by renanlecaro** [comment] 2021-03-20 15:59
Closing as duplicated of https://github.com/renanlecaro/mermaid-gdocs/issues/13

**Closed as completed by renanlecaro** 2021-03-20 15:59 UTC
